"""
PharmaCheck — Base de datos de medicamentos (migrada desde el HTML original)
"""

MEDS = {
    "paracetamol": {
        "name": "Paracetamol",
        "aka": ["acetaminofén", "acetaminophen", "tylenol", "gelocatil", "efferalgan", "termalgín"],
        "class": "Analgésico / Antipirético",
        "emoji": "💊",
        "dosage": "500–1000 mg cada 6–8 h (máx 4 g/día)",
        "uses": "Alivio del dolor leve a moderado (cefalea, dolor dental, muscular, articular), reducción de la fiebre. Primera línea en embarazo y niños.",
        "sideEffects": ["Raramente: reacciones cutáneas (urticaria)", "Hepatotoxicidad con dosis elevadas o alcohol", "Raramente: agranulocitosis"],
        "restrictions": ["Insuficiencia hepática severa", "Alcoholismo crónico", "Hipersensibilidad al paracetamol"],
        "notFor": ["Pacientes con daño hepático grave", "No superar 4 g/día en adultos", "No combinar con alcohol"],
        "fact": "El paracetamol es uno de los analgésicos más prescritos del mundo. A pesar de su aparente inocuidad, es la principal causa de insuficiencia hepática aguda en países occidentales cuando se toma en sobredosis.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Acetaminophen"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB00316"},
            {"label": "AEMPS", "url": "https://cima.aemps.es"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "suitable",        "note": "Es el analgésico de primera elección durante el embarazo cuando se usa a dosis mínimas efectivas y por el menor tiempo posible."},
            "allergy_nsaid":{"verdict": "suitable",        "note": "Buena alternativa para pacientes alérgicos a AINEs ya que no es un AINE."},
            "gastric":      {"verdict": "suitable",        "note": "No irrita la mucosa gástrica; adecuado en pacientes con úlceras o gastritis."},
            "renal":        {"verdict": "suitable",        "note": "Preferible a AINEs en insuficiencia renal leve-moderada. Ajustar dosis en insuficiencia severa."},
            "hepatic":      {"verdict": "not-recommended", "note": "Contraindicado o uso con extrema cautela en hepatopatía severa."},
            "child":        {"verdict": "suitable",        "note": "Apto para niños con dosis ajustada al peso (10–15 mg/kg cada 6 h)."},
            "elderly":      {"verdict": "suitable",        "note": "Primera opción en ancianos; mejor perfil de seguridad cardiovascular y gastrointestinal que AINEs."},
            "alternatives": ["Ibuprofeno", "Naproxeno"],
        },
    },

    "ibuprofeno": {
        "name": "Ibuprofeno",
        "aka": ["ibuprofen", "advil", "nurofen", "dalsy", "espidifen", "brufen"],
        "class": "AINE (Antiinflamatorio No Esteroideo)",
        "emoji": "🔵",
        "dosage": "200–400 mg cada 6–8 h (máx 1200 mg/día sin prescripción; 2400 mg con)",
        "uses": "Dolor leve-moderado, fiebre, inflamación, dismenorrea, cefalea tensional, artritis, lumbalgia, dolor dental, post-quirúrgico.",
        "sideEffects": ["Irritación gastrointestinal, náuseas", "Úlcera péptica (uso prolongado)", "Retención de líquidos", "Elevación leve de TA", "Raramente: hepatotoxicidad, reacción alérgica"],
        "restrictions": ["Úlcera péptica activa", "Insuficiencia renal grave", "Insuficiencia cardiaca grave", "Tercer trimestre del embarazo", "Menores de 3 meses"],
        "notFor": ["3er trimestre embarazo (cierre ductus arterioso)", "Pacientes con riesgo cardiovascular alto", "Alérgicos a AINEs o aspirina"],
        "fact": "El ibuprofeno fue desarrollado originalmente como tratamiento para la artritis reumatoide en los años 60. Es tan versátil que la OMS lo incluye en su Lista de Medicamentos Esenciales.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Ibuprofen"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB01050"},
            {"label": "AEMPS", "url": "https://cima.aemps.es"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "not-recommended", "note": "Contraindicado en el 3er trimestre (riesgo de cierre prematuro del ductus arterioso). Evitar también en 1er y 2do trimestre cuando sea posible."},
            "allergy_nsaid":{"verdict": "not-recommended", "note": "Contraindicado en pacientes con hipersensibilidad a AINEs o aspirina (reactividad cruzada)."},
            "gastric":      {"verdict": "risky",           "note": "Riesgo de irritación gástrica y úlcera; usar con protector gástrico (omeprazol) si es necesario."},
            "renal":        {"verdict": "risky",           "note": "Los AINEs reducen la perfusión renal. Contraindicado en insuficiencia renal grave."},
            "hepatic":      {"verdict": "risky",           "note": "Usar con cautela; preferir paracetamol en hepatopatía."},
            "child":        {"verdict": "suitable",        "note": "Apto para niños >3 meses a 5–10 mg/kg cada 6–8 h."},
            "elderly":      {"verdict": "risky",           "note": "Mayor riesgo de hemorragia GI y eventos cardiovasculares. Usar menor dosis efectiva con protección gástrica."},
            "alternatives": ["Paracetamol", "Naproxeno", "Diclofenaco"],
        },
    },

    "aspirina": {
        "name": "Aspirina (AAS)",
        "aka": ["aspirin", "ácido acetilsalicílico", "aas", "acido acetilsalicilico", "acetylsalicylic acid", "asa"],
        "class": "AINE / Antiagregante plaquetario",
        "emoji": "⚪",
        "dosage": "Analgesia: 500–1000 mg/6–8h. Antiagregación: 100 mg/día",
        "uses": "Dolor leve-moderado, fiebre, inflamación; prevención de eventos cardiovasculares (IAM, ACV) en dosis bajas; antiagregación plaquetaria.",
        "sideEffects": ["Irritación y sangrado gastrointestinal", "Tinnitus con dosis altas", "Síndrome de Reye en niños (menores de 16 años)", "Reacciones de hipersensibilidad"],
        "restrictions": ["Niños y adolescentes menores de 16 años con fiebre viral", "Úlcera péptica activa", "Hemofilia", "Embarazo (esp. 3er trimestre)", "Alergia a AINEs"],
        "notFor": ["Síndrome de Reye en niños febriles", "Hemofilia o trastornos hemorrágicos", "Pacientes con alergia a salicilatos"],
        "fact": "La aspirina es uno de los medicamentos más antiguos del mundo: el ácido salicílico ya era usado por los griegos y egipcios hace más de 3.500 años. En 1899, Bayer la registró con su nombre comercial.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Aspirin"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB00945"},
            {"label": "ACC/AHA Guidelines", "url": "https://www.heart.org"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "risky",           "note": "Contraindicada en dosis analgésicas durante el embarazo. Dosis bajas (100 mg) pueden usarse bajo supervisión médica estricta en preeclampsia."},
            "allergy_nsaid":{"verdict": "not-recommended", "note": "Contraindicada. La alergia a aspirina/salicilatos puede presentar reactividad cruzada con otros AINEs."},
            "gastric":      {"verdict": "risky",           "note": "Riesgo significativo de sangrado GI. Usar siempre con protección gástrica si el uso es crónico."},
            "renal":        {"verdict": "risky",           "note": "Evitar en insuficiencia renal; los salicilatos se acumulan y pueden empeorar la función renal."},
            "child":        {"verdict": "not-recommended", "note": "Contraindicada en menores de 16 años con cuadros virales febriles por riesgo de síndrome de Reye."},
            "elderly":      {"verdict": "risky",           "note": "Mayor riesgo hemorrágico. Si se usa como antiagregante, valorar riesgo/beneficio con médico."},
            "alternatives": ["Paracetamol", "Ibuprofeno", "Clopidogrel (antiagregación)"],
        },
    },

    "amoxicilina": {
        "name": "Amoxicilina",
        "aka": ["amoxicillin", "amoxil", "augmentine", "clavamox", "flemoxin"],
        "class": "Antibiótico betalactámico (penicilina)",
        "emoji": "🟡",
        "dosage": "Adultos: 250–500 mg cada 8 h o 875 mg cada 12 h. Niños: 25–45 mg/kg/día",
        "uses": "Infecciones bacterianas del tracto respiratorio (faringitis, sinusitis, neumonía), otitis media, infecciones urinarias, infecciones de piel, erradicación de H. pylori (en combinación).",
        "sideEffects": ["Diarrea, náuseas, vómitos (frecuentes)", "Exantema cutáneo", "Raramente: anafilaxia", "Sobreinfección por Candida"],
        "restrictions": ["Alergia a penicilinas o betalactámicos", "Precaución en insuficiencia renal (ajuste de dosis)", "Mononucleosis infecciosa (riesgo de rash)"],
        "notFor": ["Pacientes alérgicos a penicilinas", "Infecciones virales (antibiótico sin efecto)", "No usar sin diagnóstico bacteriano confirmado"],
        "fact": "La amoxicilina es la penicilina oral más prescrita del mundo. Fue desarrollada en 1972 como una mejora de la ampicilina con mejor absorción oral y menor frecuencia de dosis.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Amoxicillin"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB01060"},
            {"label": "AEMPS", "url": "https://cima.aemps.es"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "suitable",  "note": "Considerada segura durante el embarazo (categoría B). Se usa ampliamente para infecciones bacterianas en embarazadas."},
            "allergy_nsaid":{"verdict": "suitable",  "note": "La alergia a AINEs no interfiere con amoxicilina. Verificar alergia específica a penicilinas."},
            "gastric":      {"verdict": "suitable",  "note": "Puede tomarse con o sin alimentos. Puede causar molestias GI leves; tomar con comida si hay intolerancia."},
            "renal":        {"verdict": "risky",     "note": "Ajustar dosis en insuficiencia renal. Vigilar acumulación del fármaco."},
            "child":        {"verdict": "suitable",  "note": "Ampliamente utilizado en pediatría a dosis ajustadas al peso."},
            "elderly":      {"verdict": "suitable",  "note": "Generalmente bien tolerado. Ajustar según función renal en ancianos."},
            "alternatives": ["Azitromicina", "Claritromicina", "Cefalexina"],
        },
    },

    "metformina": {
        "name": "Metformina",
        "aka": ["metformin", "glucophage", "diaformin", "fortamet", "glumetza"],
        "class": "Antidiabético biguanida",
        "emoji": "🔴",
        "dosage": "500–850 mg 2–3 veces/día con las comidas (máx 3000 mg/día)",
        "uses": "Diabetes mellitus tipo 2 como primera línea de tratamiento, síndrome de ovario poliquístico, prevención de diabetes tipo 2 en prediabetes.",
        "sideEffects": ["Náuseas, diarrea, vómitos (especialmente al inicio)", "Sabor metálico", "Raramente: acidosis láctica (muy infrecuente)", "Déficit de vitamina B12 a largo plazo"],
        "restrictions": ["Insuficiencia renal (eGFR < 30 ml/min)", "Insuficiencia hepática", "Acidosis metabólica", "Alcoholismo", "Embarazo (decisión individualizada)"],
        "notFor": ["Insuficiencia renal severa", "Contraste yodado intravenoso (suspender temporalmente)", "Ayuno prolongado o cirugía mayor"],
        "fact": "La metformina fue descubierta a partir de la planta Galega officinalis (lila de cabra), usada en la medicina popular europea para tratar síntomas similares a la diabetes. Está en la lista de medicamentos esenciales de la OMS.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Metformin"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB00331"},
            {"label": "ADA Standards", "url": "https://diabetesjournals.org/care/issue/47/Supplement_1"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "risky",           "note": "Uso en embarazo es controvertido. Insulina sigue siendo el estándar para diabetes gestacional, aunque metformina se usa en algunos protocolos bajo supervisión."},
            "allergy_nsaid":{"verdict": "suitable",        "note": "Sin interacción relevante con alergias a AINEs."},
            "gastric":      {"verdict": "risky",           "note": "Puede agravar síntomas gastrointestinales. Tomar siempre con comida y titulación lenta."},
            "renal":        {"verdict": "not-recommended", "note": "Contraindicada en insuficiencia renal severa (eGFR <30). Ajustar en moderada."},
            "hepatic":      {"verdict": "not-recommended", "note": "Contraindicada en hepatopatía severa por riesgo de acidosis láctica."},
            "child":        {"verdict": "risky",           "note": "Uso en mayores de 10 años con DM2 aprobado; no para menores de 10 años en la mayoría de guías."},
            "elderly":      {"verdict": "risky",           "note": "Vigilar función renal en ancianos. Puede usarse si eGFR >45, con revisiones periódicas."},
            "alternatives": ["Sitagliptina", "Empagliflozina", "Insulina"],
        },
    },

    "omeprazol": {
        "name": "Omeprazol",
        "aka": ["omeprazole", "prilosec", "losec", "mopral", "omifin"],
        "class": "Inhibidor de la bomba de protones (IBP)",
        "emoji": "🟣",
        "dosage": "20–40 mg una vez al día, antes del desayuno",
        "uses": "Úlcera gástrica y duodenal, ERGE (reflujo gastroesofágico), gastritis, síndrome de Zollinger-Ellison, protección gástrica con AINEs.",
        "sideEffects": ["Cefalea, náuseas, diarrea (leves)", "Uso prolongado: déficit de magnesio, vitamina B12 y calcio", "Aumento del riesgo de infecciones entéricas (Clostridium)", "Raramente: nefritis intersticial"],
        "restrictions": ["Uso concomitante con clopidogrel (reduce efecto antiagregante)", "Precaución en hepatopatía severa", "No se recomienda tratamiento >8 semanas sin reevaluación"],
        "notFor": ["No usar sin causa justificada a largo plazo", "Interacción con clopidogrel (preferir pantoprazol)"],
        "fact": "Los inhibidores de la bomba de protones como el omeprazol son los fármacos más vendidos del mundo. Sin embargo, estudios recientes muestran que hasta el 70% de las prescripciones podrían ser innecesarias.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Omeprazole"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB00338"},
            {"label": "AEMPS", "url": "https://cima.aemps.es"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "risky",    "note": "Datos limitados. Se prefiere usar con precaución y solo si el beneficio supera el riesgo; se considera relativamente seguro en 2do y 3er trimestre."},
            "allergy_nsaid":{"verdict": "suitable", "note": "Útil como protección gástrica en pacientes que necesitan AINEs y tienen riesgo gastrointestinal."},
            "gastric":      {"verdict": "suitable", "note": "Primera línea para protección y tratamiento de patologías gástricas."},
            "renal":        {"verdict": "suitable", "note": "Generalmente bien tolerado en insuficiencia renal."},
            "child":        {"verdict": "risky",    "note": "Uso en niños >1 año posible en ERGE severo bajo supervisión médica. No recomendado en menores de 1 año."},
            "elderly":      {"verdict": "suitable", "note": "Ampliamente usado en ancianos. Vigilar déficit de magnesio y B12 en uso crónico."},
            "alternatives": ["Pantoprazol", "Lansoprazol", "Ranitidina (H2)"],
        },
    },

    "azitromicina": {
        "name": "Azitromicina",
        "aka": ["azithromycin", "zithromax", "sumamed"],
        "class": "Antibiótico macrólido",
        "emoji": "🔵",
        "dosage": "500 mg/día los primeros 3 días o 500 mg día 1, luego 250 mg días 2-5",
        "uses": "Infecciones respiratorias (neumonía atípica, bronquitis, faringitis), ITS (clamidia), otitis media, infecciones de piel.",
        "sideEffects": ["Náuseas, diarrea, dolor abdominal", "Raramente: prolongación QT, arritmias", "Toxicidad hepática (infrecuente)"],
        "restrictions": ["Hepatopatía grave", "Prolongación QT conocida", "Hipersensibilidad a macrólidos"],
        "notFor": ["Pacientes con arritmias cardiacas", "No usar en infecciones virales"],
        "fact": "La azitromicina tiene una vida media de eliminación extremadamente larga (~68 horas), lo que permite pautas de tratamiento cortas de solo 3 a 5 días.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Azithromycin"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB00207"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "risky",    "note": "Datos limitados; uso con precaución y solo si el beneficio supera el riesgo."},
            "allergy_nsaid":{"verdict": "suitable", "note": "Sin interacción relevante con alergia a AINEs."},
            "gastric":      {"verdict": "risky",    "note": "Puede causar molestias GI. Tomar con estómago vacío o con comida si hay intolerancia."},
            "child":        {"verdict": "suitable", "note": "Apto para niños con dosis ajustadas al peso (10 mg/kg/día)."},
            "elderly":      {"verdict": "risky",    "note": "Vigilar riesgo de prolongación QT y función hepática en ancianos."},
            "alternatives": ["Amoxicilina", "Claritromicina", "Doxiciclina"],
        },
    },

    "diclofenaco": {
        "name": "Diclofenaco",
        "aka": ["diclofenac", "voltaren", "cataflam", "flector"],
        "class": "AINE (Antiinflamatorio No Esteroideo)",
        "emoji": "🟠",
        "dosage": "25–75 mg 2–3 veces/día (oral); gel tópico al 1-2%",
        "uses": "Dolor musculoesquelético, artritis, lumbalgia, dismenorrea, dolor postoperatorio, gota aguda.",
        "sideEffects": ["Irritación gastrointestinal", "Retención hídrica", "Elevación de transaminasas", "Riesgo cardiovascular con uso prolongado"],
        "restrictions": ["Insuficiencia cardiaca, renal o hepática graves", "Úlcera péptica", "Tercer trimestre embarazo"],
        "notFor": ["Pacientes con insuficiencia cardiaca", "Postoperatorio de cirugía coronaria"],
        "fact": "El diclofenaco tópico en gel tiene una eficacia comparable a la forma oral para dolor musculoesquelético localizado, con muchos menos efectos sistémicos.",
        "sources": [
            {"label": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/compound/Diclofenac"},
            {"label": "DrugBank", "url": "https://go.drugbank.com/drugs/DB00586"},
        ],
        "compat": {
            "pregnancy":    {"verdict": "not-recommended", "note": "Contraindicado en el 3er trimestre. Evitar si es posible en toda la gestación."},
            "allergy_nsaid":{"verdict": "not-recommended", "note": "Contraindicado en alergia a AINEs o aspirina."},
            "gastric":      {"verdict": "risky",           "note": "Riesgo GI significativo. Combinar con protección gástrica (IBP)."},
            "elderly":      {"verdict": "risky",           "note": "Mayor riesgo cardiovascular y GI. Usar la menor dosis eficaz el menor tiempo posible."},
            "alternatives": ["Paracetamol", "Ibuprofeno tópico", "Naproxeno"],
        },
    },
}
